name: ciprianbandu
favicon: null
layout_spectrum: 0.9055191809311509
typography_spectrum: 0.739827785640955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2467682498972863
  lightness: 0.378964381525293
  saturation: 0.5729247571434826
  rhythmicContrast: 0.8834543928969651
purpose: []
